import type { Stats } from "../types/stats";

/**
 * 스탯 키 -> 화면에 뜰 이름.
 * "이 수치가 어디서 왔는지" 펼쳐 보이는 자리에서 "무엇을" 얹었는지 적을 때 쓴다.
 * 피해 공식 창(DamageFormulaModal)과 캐릭터 관리 스탯 내역이 같은 이름을 쓰도록 여기 모았다.
 * 적히지 않은 칸은 키 이름이 그대로 뜬다.
 */
export const STAT_NAMES: Partial<Record<keyof Stats, string>> = {
  hp: "HP",
  hpPercent: "HP %",
  atk: "공격력",
  atkPercent: "공격력 %(스탯창)",
  atkPercentBuff: "공격력 %(버프)",
  def: "방어력",
  defPercent: "방어력 %(스탯창)",
  defPercentBuff: "방어력 %(버프)",
  hpPercentBuff: "HP %(버프)",
  critRate: "크리티컬 확률",
  critDamage: "크리티컬 피해",
  energyRegen: "공명 효율",
  allDamageBonus: "피해증가(전체)",
  basicDamageBonus: "일반 공격 피해증가",
  heavyDamageBonus: "강공격 피해증가",
  skillDamageBonus: "공명 스킬 피해증가",
  liberationDamageBonus: "공명 해방 피해증가",
  introDamageBonus: "반주 스킬 피해증가",
  outroDamageBonus: "변주 스킬 피해증가",
  echoDamageBonus: "에코 피해증가",
  glacioDamageBonus: "응결 피해증가",
  fusionDamageBonus: "용융 피해증가",
  aeroDamageBonus: "기류 피해증가",
  electroDamageBonus: "전도 피해증가",
  spectroDamageBonus: "회절 피해증가",
  havocDamageBonus: "인멸 피해증가",
  allBoost: "부스트(전체)",
  basicBoost: "일반 공격 부스트",
  heavyBoost: "강공격 부스트",
  skillBoost: "공명 스킬 부스트",
  liberationBoost: "공명 해방 부스트",
  glacioBoost: "응결 부스트",
  fusionBoost: "용융 부스트",
  aeroBoost: "기류 부스트",
  electroBoost: "전도 부스트",
  spectroBoost: "회절 부스트",
  havocBoost: "인멸 부스트",
  motionValueAmplify: "계수 상승",
  motionValueIncrease: "계수 증가",
  defIgnore: "방어력 무시",
  defReduction: "방어력 감소",
  resPen: "저항 무시",
  resReduction: "저항 감소",
  damageTakenBonus: "받는 피해",
  totalDamageBonus: "최종 피해",
  syncAmplify: "조화도 파괴 증폭",
  discordEfficiency: "부조화 수치 누적 효율",
  coordinatedDamageBonus: "협동 공격 피해증가",
  physicalDamageBonus: "물리 피해증가",
  healingBonus: "치료 효과 보너스",
  physicalRes: "물리 피해 저항",
  glacioRes: "응결 피해 저항",
  fusionRes: "용융 피해 저항",
  electroRes: "전도 피해 저항",
  aeroRes: "기류 피해 저항",
  spectroRes: "회절 피해 저항",
  havocRes: "인멸 피해 저항",
};
